server {
    listen 80;
    #server_name take values as www.example.com, example.com
    server_name 127.0.0.1; 
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Esta regla evita errores 404 en Single Page Applications (SPA)
    # Le dice a Nginx: "Si no encuentras el archivo exacto, sirve el index.html"
    location / {
        try_files $uri $uri/ /index.html;
    }
}